
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='eventz-aws',
    version='0.5.0',
    description='AWS additions for Eventz framework.',
    python_requires='==3.*,>=3.8.0',
    author='Dan Ballance',
    author_email='work@danballance.uk',
    packages=['eventz_aws'],
    package_dir={"": "."},
    package_data={},
    install_requires=['boto3==1.*,>=1.14.16', 'boto3-stubs==1.*,>=1.15.11', 'eventz', 'immutables==0.*,>=0.14.0'],
    dependency_links=['git+git@github.com:Eventz-Framework/eventz.git@develop#egg=eventz'],
    extras_require={"dev": ["moto==1.*,>=1.3.14", "pytest==5.*,>=5.2.0", "pytest-cover==3.*,>=3.0.0"]},
)
